//! The rest of Details: the network, what else uses the CPU, Steam launch
//! options that cannot work, and the support report.
//!
//! Nothing here changes the system unless asked, and every action is
//! confirmed first: closing or pausing a background program of the user's
//! own (never a part of the system, the desktop, the game or Big Game Mode),
//! and clearing Steam launch options that call a program which is not
//! installed, with Steam closed and a backup kept. The report is generated by
//! `bigame_core::diagnostics`, which strips personal identifiers as it builds
//! rather than filtering afterwards.

use adw::prelude::*;
use gtk4::{gio, glib};
use libadwaita as adw;

use std::cell::RefCell;
use std::rc::Rc;
use std::time::Duration;

use bigame_core::network::{self, Resolver};
use bigame_core::processes;

use crate::i18n::{error_text, i18n};
use crate::widgets::toast;

/// Domains queried by the DNS benchmark.
///
/// Distinct names on purpose: querying one repeatedly measures the resolver's
/// cache rather than the resolver, and a cold lookup is what a game launcher
/// actually performs.
const PROBE_DOMAINS: &[&str] = &[
    "steamcommunity.com",
    "store.steampowered.com",
    "epicgames.com",
    "gog.com",
    "ea.com",
    "ubisoft.com",
    "battle.net",
    "riotgames.com",
    "playstation.com",
    "xbox.com",
    "nvidia.com",
    "amd.com",
];

/// Measures the background load again.
type Refresh = Rc<dyn Fn()>;

/// What else is using the CPU right now, and — for the programs that are
/// safe to touch — Close, Pause and Resume.
///
/// Nothing happens on its own. Deprioritising a process is easy; the hard
/// part is being right about *which* one. A compile left running
/// deliberately, a video export someone is waiting on, a browser playing the
/// music they are listening to: each looks identical to "background load"
/// from `/proc`. So the user decides, one program at a time, after a dialog
/// that says what the action costs.
///
/// Which programs get buttons is `bigame_core::processes::protection`'s
/// decision, and it is narrow: the user's own programs that are not part of
/// the system, the desktop, the running game or Big Game Mode. It is checked
/// again when the action runs, so a list measured before a game started
/// cannot be used to pause the game.
pub fn background_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Background load"));
    group.set_description(Some(&i18n(
        "Programs of yours using noticeable CPU. Closing or pausing them frees \
         it for a game — but only you know which ones you are actually using. \
         Parts of the system, the desktop, the game and Big Game Mode have no \
         buttons.",
    )));

    let again = gtk4::Button::builder()
        .icon_name("view-refresh-symbolic")
        .tooltip_text(i18n("Measure again"))
        .valign(gtk4::Align::Center)
        .css_classes(["flat"])
        .build();
    again.update_property(&[gtk4::accessible::Property::Label(&i18n("Measure again"))]);
    group.set_header_suffix(Some(&again));

    let rows: Rc<RefCell<Vec<adw::ActionRow>>> = Rc::new(RefCell::new(Vec::new()));
    let refresh: Rc<RefCell<Option<Refresh>>> = Rc::new(RefCell::new(None));
    let measure: Rc<dyn Fn()> = {
        let group = group.clone();
        let again = again.clone();
        let rows = Rc::clone(&rows);
        // The rows' buttons measure again after acting; a weak handle keeps
        // the rows from owning the closure that owns them.
        let weak_refresh = Rc::downgrade(&refresh);
        Rc::new(move || {
            if !again.is_sensitive() {
                return;
            }
            again.set_sensitive(false);
            for row in rows.borrow_mut().drain(..) {
                group.remove(&row);
            }
            let placeholder = adw::ActionRow::builder()
                .title(i18n("Measuring…"))
                .sensitive(false)
                .build();
            group.add(&placeholder);
            rows.borrow_mut().push(placeholder);

            let group = group.clone();
            let again = again.clone();
            let rows = Rc::clone(&rows);
            let weak_refresh = weak_refresh.clone();
            glib::spawn_future_local(async move {
                // Sampling needs two readings a second or so apart — cumulative
                // CPU time from one reading says nothing about the present.
                let game = crate::game_watch::current();
                let (busy, paused) = gio::spawn_blocking(move || {
                    (
                        processes::busy_processes(Duration::from_secs(2), game.as_ref()),
                        processes::paused(),
                    )
                })
                .await
                .unwrap_or_default();

                for row in rows.borrow_mut().drain(..) {
                    group.remove(&row);
                }
                let anchor = group.clone().upcast::<gtk4::Widget>();
                let after = move || {
                    if let Some(refresh) = weak_refresh.upgrade() {
                        let refresh = refresh.borrow().clone();
                        if let Some(refresh) = refresh {
                            refresh();
                        }
                    }
                };
                let after: Rc<dyn Fn()> = Rc::new(after);
                let mut new_rows = Vec::new();
                // Paused programs use no CPU, so they are never "busy": listed
                // on their own, first, so the way back is never out of sight.
                for target in paused {
                    new_rows.push(paused_row(target, &anchor, &after));
                }
                for process in busy {
                    new_rows.push(busy_row(&process, &anchor, &after));
                }
                if new_rows.is_empty() {
                    let row = adw::ActionRow::builder()
                        .title(i18n("Nothing competing for the CPU"))
                        .subtitle(i18n("No program of yours is using a noticeable share."))
                        .build();
                    row.add_prefix(&status_icon(true));
                    new_rows.push(row);
                }
                for row in new_rows {
                    group.add(&row);
                    rows.borrow_mut().push(row);
                }
                again.set_sensitive(true);
            });
        })
    };
    *refresh.borrow_mut() = Some(Rc::clone(&measure));
    measure();
    // The button holds the one strong handle, so the closure lives as long
    // as the group does.
    again.connect_clicked(move |_| {
        let measure = refresh.borrow().clone();
        if let Some(measure) = measure {
            measure();
        }
    });

    group
}

/// One busy program: what it is, and — if it is safe to touch — Pause and
/// Close.
fn busy_row(
    process: &processes::BusyProcess,
    anchor: &gtk4::Widget,
    after: &Rc<dyn Fn()>,
) -> adw::ActionRow {
    let row = adw::ActionRow::builder()
        .title(&process.name)
        .subtitle(format!(
            "{} · {} MiB · {}",
            i18n("%s% of one CPU").replace("%s", &format!("{:.0}", process.cpu_percent)),
            process.memory_mib,
            i18n(process.kind.describe())
        ))
        .build();
    row.add_prefix(&gtk4::Image::from_icon_name(match process.kind {
        processes::Kind::Browser => "web-browser-symbolic",
        processes::Kind::Gaming => "applications-games-symbolic",
        processes::Kind::Media => "video-x-generic-symbolic",
        processes::Kind::Virtualisation => "computer-symbolic",
        processes::Kind::Desktop => "preferences-desktop-symbolic",
        processes::Kind::ThisApp => "com.biglinux.BiGameMode",
        _ => "system-run-symbolic",
    }));

    if !process.controllable {
        // No buttons, and a word on why, so their absence is not a mystery.
        let lock = gtk4::Image::from_icon_name("changes-prevent-symbolic");
        lock.add_css_class("dim-label");
        let why = i18n(
            "Part of the system, your desktop, the running game or Big Game Mode: \
             it cannot be closed or paused from here.",
        );
        lock.set_tooltip_text(Some(&why));
        lock.update_property(&[gtk4::accessible::Property::Label(&why)]);
        row.add_suffix(&lock);
        return row;
    }

    let target = process.target();
    let pause = gtk4::Button::builder()
        .label(i18n("Pause"))
        .valign(gtk4::Align::Center)
        .css_classes(["flat"])
        .build();
    {
        let (target, anchor, after) = (target.clone(), anchor.clone(), Rc::clone(after));
        pause.connect_clicked(move |button| {
            let body = i18n(
                "It freezes completely until you resume it: its windows stop \
                 responding, and any sound, download or call in it stops. A \
                 program that talks to a server may lose its connection. \
                 Resume it here when you are done — Big Game Mode also resumes it \
                 when Big Game Mode quits.",
            );
            confirm(
                button,
                &i18n("Pause %s?").replace("%s", &target.name),
                &body,
                &i18n("Pause"),
                adw::ResponseAppearance::Suggested,
                act(
                    Action::Pause,
                    target.clone(),
                    anchor.clone(),
                    Rc::clone(&after),
                ),
            );
        });
    }
    row.add_suffix(&pause);

    let close = gtk4::Button::builder()
        .label(i18n("Close"))
        .valign(gtk4::Align::Center)
        .css_classes(["flat", "destructive-action"])
        .build();
    {
        let (anchor, after) = (anchor.clone(), Rc::clone(after));
        close.connect_clicked(move |button| {
            let body = i18n(
                "Big Game Mode asks it to quit, as closing its window would \
                 (SIGTERM). Anything you have not saved in it may be lost. A \
                 program that ignores the request keeps running: nothing \
                 forces it.",
            );
            confirm(
                button,
                &i18n("Close %s?").replace("%s", &target.name),
                &body,
                &i18n("Close"),
                adw::ResponseAppearance::Destructive,
                act(
                    Action::Close,
                    target.clone(),
                    anchor.clone(),
                    Rc::clone(&after),
                ),
            );
        });
    }
    row.add_suffix(&close);
    row
}

/// A program Big Game Mode paused, with the way back.
fn paused_row(
    target: processes::Target,
    anchor: &gtk4::Widget,
    after: &Rc<dyn Fn()>,
) -> adw::ActionRow {
    let row = adw::ActionRow::builder()
        .title(&target.name)
        .subtitle(i18n(
            "Paused by Big Game Mode — frozen, using no CPU, until you resume it.",
        ))
        .build();
    let icon = gtk4::Image::from_icon_name("media-playback-pause-symbolic");
    icon.add_css_class("warning");
    row.add_prefix(&icon);

    let resume = gtk4::Button::builder()
        .label(i18n("Resume"))
        .valign(gtk4::Align::Center)
        .css_classes(["suggested-action"])
        .build();
    let (anchor, after) = (anchor.clone(), Rc::clone(after));
    resume.connect_clicked(move |button| {
        confirm(
            button,
            &i18n("Resume %s?").replace("%s", &target.name),
            &i18n(
                "It carries on from where it was paused and starts using the \
                 CPU again.",
            ),
            &i18n("Resume"),
            adw::ResponseAppearance::Suggested,
            act(
                Action::Resume,
                target.clone(),
                anchor.clone(),
                Rc::clone(&after),
            ),
        );
    });
    row.add_suffix(&resume);
    row
}

#[derive(Clone, Copy)]
enum Action {
    Close,
    Pause,
    Resume,
}

/// Ask before acting: the heading names the program, the body says what the
/// action costs, and Cancel is what Enter and Escape choose.
fn confirm(
    parent: &impl IsA<gtk4::Widget>,
    heading: &str,
    body: &str,
    action_label: &str,
    appearance: adw::ResponseAppearance,
    on_confirm: impl Fn() + 'static,
) {
    let dialog = adw::AlertDialog::builder()
        .heading(heading)
        .body(format!("{body}\n\n{}", i18n("Are you sure?")))
        .build();
    dialog.add_response("cancel", &i18n("Cancel"));
    dialog.add_response("confirm", action_label);
    dialog.set_response_appearance("confirm", appearance);
    dialog.set_default_response(Some("cancel"));
    dialog.set_close_response("cancel");
    dialog.connect_response(None, move |_, response| {
        if response == "confirm" {
            on_confirm();
        }
    });
    dialog.present(Some(parent));
}

/// Run `action` on `target` off the main thread, against a guard read at
/// that moment (the game may have started since the list was measured), and
/// say what happened.
fn act(
    action: Action,
    target: processes::Target,
    anchor: gtk4::Widget,
    after: Rc<dyn Fn()>,
) -> impl Fn() + 'static {
    move || {
        let (target, anchor, after) = (target.clone(), anchor.clone(), Rc::clone(&after));
        glib::spawn_future_local(async move {
            let game = crate::game_watch::current();
            let name = target.name.clone();
            let result = gio::spawn_blocking(move || {
                let guard = processes::Guard::new(game.as_ref());
                match action {
                    Action::Close => processes::close(&target, &guard),
                    Action::Pause => processes::pause(&target, &guard),
                    Action::Resume => processes::resume(&target),
                }
            })
            .await;
            match result {
                Ok(Ok(())) => toast::show(
                    &anchor,
                    &match action {
                        Action::Close => i18n("Asked %s to close"),
                        Action::Pause => i18n("%s paused"),
                        Action::Resume => i18n("%s resumed"),
                    }
                    .replace("%s", &name),
                ),
                Ok(Err(e)) => toast::error(&anchor, &error_text(&e), &format!("{e:#}")),
                Err(_) => {}
            }
            // A closed program takes a moment to go; measuring at once would
            // still list it.
            if matches!(action, Action::Close) {
                glib::timeout_future(Duration::from_millis(800)).await;
            }
            after();
        });
    }
}

// ── Steam launch options ────────────────────────────────────────────────────

/// Steam launch options that name a program which is not installed.
///
/// Steam runs the string through a shell, so a missing wrapper means the game
/// simply does not start — and nothing in Steam's interface explains it. A
/// common case is `gamemoderun %command%` left behind after Feral `GameMode` is
/// uninstalled.
///
/// Clearing the option is offered rather than done. It is the user's
/// configuration, and the alternative fix — installing the missing program — is
/// equally valid and not ours to choose.
pub fn steam_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Steam launch options"));
    group.set_description(Some(&i18n(
        "Options that call a program this system does not have. Steam runs them \
         through a shell, so the game will not start.",
    )));
    group.set_visible(false);

    let rows: Rc<RefCell<Vec<adw::ActionRow>>> = Rc::new(RefCell::new(Vec::new()));
    let group_ref = group.clone();
    let rows_ref = Rc::clone(&rows);

    let refresh: Rc<dyn Fn()> = Rc::new(move || {
        for row in rows_ref.borrow_mut().drain(..) {
            group_ref.remove(&row);
        }
        let group = group_ref.clone();
        let rows = Rc::clone(&rows_ref);
        glib::spawn_future_local(async move {
            let broken = gio::spawn_blocking(scan_broken_launch_options)
                .await
                .unwrap_or_default();
            group.set_visible(!broken.is_empty());
            for entry in broken {
                let row = build_broken_row(&entry);
                group.add(&row);
                rows.borrow_mut().push(row);
            }
        });
    });
    refresh();
    // Re-scan after a fix so the row disappears instead of lingering.
    STEAM_REFRESH.with(|cell| *cell.borrow_mut() = Some(Rc::clone(&refresh)));

    group
}

thread_local! {
    /// Lets a fix handler ask the group to rebuild itself.
    static STEAM_REFRESH: RefCell<Option<Rc<dyn Fn()>>> = const { RefCell::new(None) };
}

/// One broken option, with enough context to describe it.
struct BrokenOption {
    config: std::path::PathBuf,
    app_id: String,
    title: String,
    missing: String,
    options: String,
}

fn scan_broken_launch_options() -> Vec<BrokenOption> {
    let Ok(home) = std::env::var("HOME") else {
        return Vec::new();
    };
    let home = std::path::PathBuf::from(home);
    let mut out = Vec::new();
    for user in bigame_core::steam::users(&home) {
        for broken in bigame_core::steam::broken_launch_options(&user.config) {
            out.push(BrokenOption {
                title: steam_app_name(&home, &broken.app_id),
                config: user.config.clone(),
                app_id: broken.app_id,
                missing: broken.missing,
                options: broken.options,
            });
        }
    }
    out
}

/// A game's title from its Steam manifest, or its `AppID` if it is not installed.
fn steam_app_name(home: &std::path::Path, app_id: &str) -> String {
    for root in bigame_core::games::steam_libraries(home) {
        let manifest = root.join(format!("steamapps/appmanifest_{app_id}.acf"));
        if let Ok(content) = std::fs::read_to_string(&manifest) {
            if let Some(name) = bigame_core::games::acf_value(&content, "name") {
                return name;
            }
        }
    }
    i18n("Steam app %s").replace("%s", app_id)
}

fn build_broken_row(entry: &BrokenOption) -> adw::ActionRow {
    let row = adw::ActionRow::builder()
        .title(&entry.title)
        .subtitle(
            i18n("Calls '%p', which is not installed — launch options: %o")
                .replace("%p", &entry.missing)
                .replace("%o", &entry.options),
        )
        .build();
    row.add_prefix(&{
        let icon = gtk4::Image::from_icon_name("dialog-warning-symbolic");
        icon.add_css_class("warning");
        icon
    });

    let clear = gtk4::Button::builder()
        .label(i18n("Clear launch options"))
        .valign(gtk4::Align::Center)
        .build();

    let config = entry.config.clone();
    let app_id = entry.app_id.clone();
    clear.connect_clicked(move |button| {
        let (config, app_id, button) = (config.clone(), app_id.clone(), button.clone());
        button.set_sensitive(false);
        // Steam's file is parsed and rewritten off the main thread.
        glib::spawn_future_local(async move {
            let done = gio::spawn_blocking(move || {
                // Steam holds this file in memory and rewrites it on exit, so
                // an edit made underneath a running client is silently
                // discarded. Say so rather than appearing to work.
                if bigame_core::steam::is_running() {
                    return None;
                }
                Some(bigame_core::steam::set_launch_options(&config, &app_id, ""))
            })
            .await;
            button.set_sensitive(true);
            match done {
                Ok(None) => toast::show(
                    &button,
                    &i18n("Close Steam first — it would overwrite this change when it exits."),
                ),
                Ok(Some(Ok(()))) => {
                    toast::show(&button, &i18n("Launch options cleared"));
                    STEAM_REFRESH.with(|cell| {
                        if let Some(refresh) = cell.borrow().as_ref() {
                            refresh();
                        }
                    });
                }
                Ok(Some(Err(e))) => toast::show(
                    &button,
                    &i18n("Could not change it: %s").replace("%s", &error_text(&e)),
                ),
                Err(_) => toast::show(
                    &button,
                    &i18n("Could not change it: %s")
                        .replace("%s", &i18n("the worker thread stopped")),
                ),
            }
        });
    });
    row.add_suffix(&clear);
    row
}

// ── Network ─────────────────────────────────────────────────────────────────

/// Building a widget tree is inherently linear — splitting it yields helpers
/// with a single caller and no independent meaning — so the length lint is
/// allowed here rather than worked around.
#[allow(clippy::too_many_lines)]
pub fn network_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Network"));
    group.set_description(Some(&i18n(
        "Measured on the connection that carries your traffic, not on every \
         interface this machine happens to have.",
    )));

    let link_row = adw::ActionRow::builder()
        .title(i18n("Connection"))
        .subtitle(i18n("Checking…"))
        .build();
    group.add(&link_row);

    let qdisc_row = adw::ActionRow::builder()
        .title(i18n("Queue discipline"))
        .subtitle(i18n("Checking…"))
        .build();
    group.add(&qdisc_row);

    // Populated once, off the main thread; nothing here changes while the page
    // is open, so there is no reason to poll it.
    {
        let link_row = link_row.clone();
        let qdisc_row = qdisc_row.clone();
        glib::spawn_future_local(async move {
            let link = gio::spawn_blocking(network::primary_link)
                .await
                .ok()
                .flatten();
            if let Some(link) = link {
                link_row.set_title(&link.name);
                link_row.set_subtitle(&format!(
                    "{} · {} · MTU {}",
                    match link.medium {
                        network::Medium::Ethernet => i18n("Wired"),
                        network::Medium::WiFi => i18n("Wi-Fi"),
                        network::Medium::Virtual => i18n("Virtual"),
                        network::Medium::Unknown => i18n("Unknown"),
                    },
                    link.speed_mbps
                        .map_or_else(|| i18n("unknown speed"), |s| format!("{s} Mb/s")),
                    link.mtu.map_or_else(|| "?".to_owned(), |m| m.to_string())
                ));

                if let Some(qdisc) = link.qdisc.as_deref() {
                    let modern = link.has_modern_qdisc();
                    qdisc_row.set_subtitle(&format!(
                        "{qdisc} — {}",
                        if modern {
                            // Saying "already good" matters: offering to
                            // enable something that is on would be a no-op
                            // reported as an improvement.
                            i18n("already manages latency under load; nothing to change")
                        } else {
                            i18n("does not actively manage latency under load")
                        }
                    ));
                    qdisc_row.add_prefix(&status_icon(modern));
                } else {
                    // No verdict on what could not be read.
                    qdisc_row.set_subtitle(&i18n(
                        "Unknown: tc (iproute2) could not read the interface's queue discipline",
                    ));
                }
            } else {
                link_row.set_subtitle(&i18n("No default route — this machine is offline"));
                qdisc_row.set_visible(false);
            }
        });
    }

    // ── DNS benchmark ───────────────────────────────────────────────────
    let dns_group = adw::ExpanderRow::builder()
        .title(i18n("DNS resolver comparison"))
        .subtitle(i18n(
            "Measures how quickly each resolver answers a lookup. It does not \
             change the round-trip time of match traffic.",
        ))
        .build();

    let run_button = gtk4::Button::builder()
        .label(i18n("Measure"))
        .valign(gtk4::Align::Center)
        .css_classes(["suggested-action"])
        .build();
    dns_group.add_suffix(&run_button);
    group.add(&dns_group);

    // What the computer uses now, and the way back from a change made here.
    let computer = super::dns::ComputerDns::new();
    group.add(computer.row());

    let rows: Rc<RefCell<Vec<adw::ActionRow>>> = Rc::new(RefCell::new(Vec::new()));
    {
        let dns_group = dns_group.clone();
        let rows = Rc::clone(&rows);
        let run_button = run_button.clone();
        run_button.clone().connect_clicked(move |_| {
            for row in rows.borrow_mut().drain(..) {
                dns_group.remove(&row);
            }
            computer.clear_buttons();
            run_button.set_sensitive(false);
            run_button.set_label(&i18n("Measuring…"));
            dns_group.set_expanded(true);

            let dns_group = dns_group.clone();
            let rows = Rc::clone(&rows);
            let run_button = run_button.clone();
            let computer = Rc::clone(&computer);
            glib::spawn_future_local(async move {
                let results = gio::spawn_blocking(run_dns_benchmark)
                    .await
                    .unwrap_or_default();

                let fastest = network::fastest(&results).map(|r| r.resolver.name.clone());
                for result in &results {
                    // With its address: that is what "Use" would set.
                    let row = adw::ActionRow::builder()
                        .title(format!(
                            "{} · {}",
                            result.resolver.name, result.resolver.address
                        ))
                        .build();
                    match &result.stats {
                        Some(stats) => {
                            row.set_subtitle(&format!(
                                "{} {:.1} ms · {} {:.1} ms · {} {:.1} ms",
                                i18n("median"),
                                stats.median_ms,
                                i18n("95th percentile"),
                                stats.p95_ms,
                                i18n("jitter"),
                                stats.jitter_ms
                            ));
                            if fastest.as_deref() == Some(result.resolver.name.as_str()) {
                                let badge = gtk4::Label::new(Some(&i18n("Fastest lookups")));
                                badge.add_css_class("caption");
                                badge.add_css_class("success");
                                badge.set_valign(gtk4::Align::Center);
                                row.add_suffix(&badge);
                            }
                            // Only a resolver that answered is worth offering.
                            if let Some(use_button) = computer.use_button(&result.resolver) {
                                row.add_suffix(&use_button);
                            }
                        }
                        None => row.set_subtitle(&i18n("No response")),
                    }
                    dns_group.add_row(&row);
                    rows.borrow_mut().push(row);
                }

                // The disclaimer is part of the result, not a footnote: the
                // whole point is that a faster resolver is not a faster game.
                let note = adw::ActionRow::builder()
                    .title(i18n("What this does not mean"))
                    .subtitle(i18n(network::dns_disclaimer()))
                    .build();
                note.add_prefix(&gtk4::Image::from_icon_name("dialog-information-symbolic"));
                dns_group.add_row(&note);
                rows.borrow_mut().push(note);

                run_button.set_sensitive(true);
                run_button.set_label(&i18n("Measure again"));
            });
        });
    }

    group
}

/// Benchmark the system resolvers plus a handful of well-known public ones.
fn run_dns_benchmark() -> Vec<network::DnsResult> {
    candidates()
        .iter()
        .map(|r| network::benchmark_resolver(r, PROBE_DOMAINS, Duration::from_secs(2)))
        .collect()
}

/// The resolvers the comparison measures, named as it shows them. Settings
/// offers the same list as ping targets.
pub fn candidates() -> Vec<Resolver> {
    network::comparison_candidates(&network::system_resolvers(), |n| {
        format!("{} #{n}", i18n("System"))
    })
}

pub fn status_icon(good: bool) -> gtk4::Image {
    let icon = gtk4::Image::from_icon_name(if good {
        "object-select-symbolic"
    } else {
        "dialog-information-symbolic"
    });
    icon.add_css_class(if good { "success" } else { "dim-label" });
    icon
}

// ── Support report ──────────────────────────────────────────────────────────

pub fn report_group() -> adw::PreferencesGroup {
    let group = adw::PreferencesGroup::new();
    group.set_title(&i18n("Support report"));
    group.set_description(Some(&i18n(
        "Everything a supporter needs about this machine. Your username, home \
         directory, hostname and public network addresses are removed as the \
         report is built.",
    )));

    let buffer = gtk4::TextBuffer::new(None);
    buffer.set_text(&i18n("Generating…"));

    let view = gtk4::TextView::builder()
        .buffer(&buffer)
        .editable(false)
        .monospace(true)
        .left_margin(12)
        .right_margin(12)
        .top_margin(12)
        .bottom_margin(12)
        .build();

    let scroll = gtk4::ScrolledWindow::builder()
        .child(&view)
        .height_request(320)
        .hscrollbar_policy(gtk4::PolicyType::Automatic)
        .build();
    scroll.add_css_class("card");

    let copy = gtk4::Button::builder().label(i18n("Copy")).build();
    let save = gtk4::Button::builder().label(i18n("Save to file…")).build();
    let refresh = gtk4::Button::builder()
        .icon_name("view-refresh-symbolic")
        .tooltip_text(i18n("Regenerate"))
        .build();

    let actions = gtk4::Box::new(gtk4::Orientation::Horizontal, 6);
    actions.set_halign(gtk4::Align::End);
    actions.set_margin_top(6);
    actions.append(&refresh);
    actions.append(&copy);
    actions.append(&save);

    let column = gtk4::Box::new(gtk4::Orientation::Vertical, 0);
    column.append(&scroll);
    column.append(&actions);
    group.add(&column);

    let generate = {
        let buffer = buffer.clone();
        move || {
            let buffer = buffer.clone();
            glib::spawn_future_local(async move {
                // Generating probes hardware, D-Bus and sysfs; it belongs off
                // the main thread even though it only takes a moment.
                let text = gio::spawn_blocking(|| bigame_core::diagnostics::report(false))
                    .await
                    .unwrap_or_else(|_| i18n("Could not generate the report."));
                buffer.set_text(&text);
            });
        }
    };
    generate();
    {
        let generate = generate.clone();
        refresh.connect_clicked(move |_| generate());
    }

    {
        let buffer = buffer.clone();
        copy.connect_clicked(move |button| {
            let text = buffer
                .text(&buffer.start_iter(), &buffer.end_iter(), false)
                .to_string();
            if let Some(display) = gtk4::gdk::Display::default() {
                display.clipboard().set_text(&text);
                toast::show(button, &i18n("Report copied"));
            }
        });
    }

    {
        let buffer = buffer.clone();
        save.connect_clicked(move |button| {
            let dialog = gtk4::FileDialog::builder()
                .title(i18n("Save diagnostics"))
                .initial_name("bigame-mode-diagnostics.txt")
                .build();
            let text = buffer
                .text(&buffer.start_iter(), &buffer.end_iter(), false)
                .to_string();
            let button = button.clone();
            let window = button.root().and_downcast::<gtk4::Window>();
            dialog.save(window.as_ref(), gio::Cancellable::NONE, move |result| {
                let Ok(file) = result else { return };
                let Some(path) = file.path() else { return };
                match std::fs::write(&path, text.as_bytes()) {
                    Ok(()) => toast::show(&button, &i18n("Report saved")),
                    Err(e) => toast::show(
                        &button,
                        &i18n("Could not save: %s").replace("%s", &e.to_string()),
                    ),
                }
            });
        });
    }

    group
}
